### ISSUE TITLE
Exported parameter ValueCheckingMode has or is using private name ('Anonymous class').

### ISSUE THREAD

**Issue by musicEnfanthen** [dhlab-basel/json2typescript#1]
On Windows 7, 64-bit (using Node v6.9.0, FF, angular2 v2.23, angular-cli v1.0.0-beta.22-1, typescript v~2.0.3) I get the error message 

> Exported parameter ValueCheckingMode has or is using private name ('Anonymous class').

when trying to `ng serve ` a project using `json2typescript` package. Tried it with [SALSAH](https://github.com/dhlab-basel/Salsah) (using json2typescript v0.9.3) and a completely new TestApplication as described in the README here (with latest v0.9.5). 

Changing

`public static ValueCheckingMode = class {
`

to

`public static ValueCheckingMode: any = class {`

did the trick, but I'm not sure whether it is the best possible type nor solution. It's somehow connected to [this old TypeScript issue](https://github.com/Microsoft/TypeScript/issues/6307).

On MacOS X (also Node v6.9.0., FF) I could not reproduce this error, it's running without problems.

**Comment by andreas-aeschlimann** [comment]
Have you tried upgrading TypeScript? It seems like this issue is resolved in later versions.

Tested with:
angular-cli 1.0.0-beta.25.5
typescript 2.1.4
json2typescript 0.9.5

Make sure you upgrade angular-cli, because there were issues with TypeScript 2.1.x and earlier angular-cli versions.

**Comment by musicEnfanthen** [comment]
Sorry for the late reply, I had to wait upgrading typescript or angular-cli for several reasons. And thanks for the hint, with angular-cli 1.0.0-beta.30.0 I don't get the error anymore.

**Comment by andreas-aeschlimann** [comment]
No worries, thanks for the feedback.

**Comment by trusktr** [comment]
I've opened a request to fix issues like these in TypeScript by bringing declaration files to parity with language features. https://github.com/microsoft/TypeScript/issues/35822
