### ISSUE TITLE
Large datasets freeze browser

### ISSUE THREAD

**Issue by JarLowrey** [dhlab-basel/json2typescript#108]
I have an array of 5500 objects, each with 27 keys. Some of these keys nest to child objects as well. 

When calling `jsonConvert.deserializeArray(myArray, ValueCheckingMode.ALLOW_NULL);` the browser CPU spikes and appears to freeze for many minutes. I have not been able to get it to finish despite long wait periods. Am I out of luck in this use case for this package?

**Comment by andreas-aeschlimann** [comment]
Is this a typo? `jsonConvert.deserializeArray(myArray, ValueCheckingMode.ALLOW_NULL);`

The second parameter here must be the type, not the ValueCheckingMode. This could never work.

In general I can say that I have used json2typescript with large nested objects as well. It is clear though that at some point you will get a performance hit. Imagine that for every object, json2typescript loops all properties and creates an instance.

In case you hit issues, I guess you cannot do much. Maybe you could only type check critical parts, or cut your data into chunks. Do you really need 5500 objects at once?

**Comment by JarLowrey** [comment]
Sorry, that was a type. second param is `repositoryType`.  This is for a "export all data to excel" function, so it's all needed. IDK if it needs to be converted to TS though, will have to see if I can do without.

**Comment by JarLowrey** [comment]
I solved this problem by rewriting the model's instance methods as static methods, and then removing the conversion to typescript.

Example:
 
```
// ------------SLOW------------
//Model.ts
@JsonProperty('WorkProjectFunds', [WorkProjectFund], true) WorkProjectFunds = new Array<WorkProjectFund>();
getTotal() {SUM_UP_THIS.WORK_PROJ_FUNDS }
 
//SomeFile.ts
let jsonResp = await API_CALL;
var m = jsonConvert.deserializeObject(jsonResp, Model); //slooooooow - 2+ hours for 5.5k deeply nested objects
return m.getTotal()
 
 
// ------------FAST------------
//Model.ts
@JsonProperty('WorkProjectFunds', [WorkProjectFund], true) WorkProjectFunds = new Array<WorkProjectFund>();
static getTotal(modelJson) { return SUM_UP_USING_modelJSON }
getTotal() { return Model.getTotal(this); } // can even still have instance methods!
 
  
//SomeFile.ts
let jsonResp = await API_CALL;
return Model.getTotal(jsonResp); //fast! 60ms
 
```

Depending on how many objects you have, and how much existing code depends on them being objects instead of JSON, you (future reader) will need to decide if optimization is worth the readability/TS typeless tradeoff

**Comment by andreas-aeschlimann** [comment]
So you removed the usage of json2typescript for this case?

**Comment by JarLowrey** [comment]
Pretty much, yes
