### ISSUE TITLE
Compiled version in NPM distribution

### ISSUE THREAD

**Issue by gempain** [dhlab-basel/json2typescript#12]
Hello !

For some reason, when I install the package with `npm`, there is no `.js` compiled version of the sources. In some situations, you can get an `Error: Cannot find module 'json2typescript'` exception at runtime.

In my case, it is because I am webpacking a NodeJS backend. Packages in `node_modules` are not packed with my sources. They depend on packages installed in `node_modules`. Hence, at runtime, my code tries to find the code for `json2typescript`, and throws the above mentioned error.

I spent a a while wondering what I was doing wrong until realising the package does not come with a compiled version.

I suggest a merge request and re-publish on `npm` :) This should only take a few minutes really, and I'd be happy to create a merge request :)

Cheers and keep up the good work !

**Comment by savanvadalia** [comment]
Not an nodejs expert still new java-script world. But may be this might this issue too which i have raised
https://github.com/dhlab-basel/json2typescript/issues/11

**Comment by andreas-aeschlimann** [comment]
I will added a compiled version to the next release. I didn't know this was necessary in that case.
