### ISSUE TITLE
NPM package for json2typescript v.0.9.5 is defective:

### ISSUE THREAD

**Issue by DRepinSLB** [dhlab-basel/json2typescript#16]
I am new to the web development, so, I might be mistaken. Having said that, it looks that the NPM package for json2typescript v.0.9.5 is defective: it contains only Typescript code and no JavaScript.
![image](https://user-images.githubusercontent.com/25776179/27739621-ddb52d7a-5d74-11e7-9cba-6ee5d2bd3f71.png)
I believe this is because the tsconfig.json contains an invalid specification for json-convert.ts. The ".ts" suffix is missing:
  "files": [
    "./index.ts",
    "./src/json2typescript/json-convert"
  ]

**Comment by andreas-aeschlimann** [comment]
It's not "defective", but there are indeed no JavaScript files. Depending on your configuration, your project might not compile the TypeScript files and leave you with errors.

I think in the new version this should be fixed (coming soon).
