### ISSUE TITLE
Feature request: add support for type resolvers

### ISSUE THREAD

**Issue by DRepinSLB** [dhlab-basel/json2typescript#18]
When a class has a property of a type that is a base class in a class hierarchy (e.g., a Manager has a report that is either another Manager or a Person), json2typescript will have a problem de-serializing it.

     @JsonObject
     export class Manager extends Person {
         @JsonProperty("report", Person)
         reports: Person | undefined = undefined;
     }

Similar problem is observed in the Microsoft WCF Data Contracts. They addressed it by allowing a custom type resolvers:
https://docs.microsoft.com/en-us/dotnet/framework/wcf/feature-details/using-a-data-contract-resolver

json2typescript could do the same. It should be possible to associate with JsonProperty a function that would supply a desired classObject to 

     deserializeObject(jsonObject: any, classObject: { new(): any })

**Comment by andreas-aeschlimann** [comment]
Thank you for this report, I will look into this if possible.

**Comment by andreas-aeschlimann** [comment]
The new version will have custom mappers, so I think this issue is resolved by this. Please report back if you think otherwise.
