### ISSUE TITLE
update README

### ISSUE THREAD

**Issue by musicEnfanthen** [dhlab-basel/json2typescript#2]
Please add the following missing statements in the TestApplication example of the README:

In `Country.ts`: 
- Add  `import { City } from "./city";`

In `app.component.ts`:

- Add OnInit to the import:  `import { Component, OnInit } from '@angular/core';`

- Replace `import { City } from "./city";` (not needed) with  `import { Country } from "./country"`;

**Comment by andreas-aeschlimann** [comment]
Will be added to next version
