### ISSUE TITLE
feature request: support for optional parameters

### ISSUE THREAD

**Issue by amarnathm** [dhlab-basel/json2typescript#20]
Hi. I've a recursive tree object, where  children are of the same type as the current object. At some point, there is a leaf node that has no children. Is there a  way to handle this in your current version? If not, would you please consider adding it?

Thanks!

**Comment by andreas-aeschlimann** [comment]
Can you show what you have tried so far? Did it fail at some point?

**Comment by andreas-aeschlimann** [comment]
Closed due to inactivity
