### ISSUE TITLE
npm lists 0.9.5 as the latest, where 1.0.0 seems available

### ISSUE THREAD

**Issue by meronbrouwer** [dhlab-basel/json2typescript#21]
README.md lists version 1.0.0, but on npm 0.9.5 is the latest available version. I would like to start using 1.0.0. When will this be available through npm?

**Comment by andreas-aeschlimann** [comment]
I'll release it tonight, I wanted to give people a chance to try it out. As I haven't got any (bad) feedback, I assume it's okay.

**Comment by andreas-aeschlimann** [comment]
Published 1.0.2 to NPM

**Comment by meronbrouwer** [comment]
Thanks.
