### ISSUE TITLE
compiling app with noImplicitAny

### ISSUE THREAD

**Issue by xblox** [dhlab-basel/json2typescript#23]
Hey, 
your lib causes implicit any errors in my app. Any chance to get rid of that ? Would you accept a PR to fix those errors ? 

thanks

**Comment by andreas-aeschlimann** [comment]
Can you show a screenshot about the error and/or specify what it concerns exactly?

Does the update prevent you from compiling or is it just a warning?

**Comment by xblox** [comment]
Hi,
thanks for the heads up !

here my app tsconfig.json : 

```json
{
	"compilerOptions": {
		"module": "commonjs",
		"target": "es6",
		"noImplicitAny": true,
		"sourceMap": true,
		"outDir": "./dist",
		"experimentalDecorators": true,
		"emitDecoratorMetadata": true,
		"pretty": true,
		"moduleResolution": "node",
		"suppressImplicitAnyIndexErrors": true
	},
	"compileOnSave": false,
	"exclude": [
		"node_modules"
	],
	"files": [
		"./src/index.ts"
	]
}
```


here the output of tsc:
```bash

612             let array = [];
                    ~~~~~

node_modules/json2typescript/src/json2typescript/json-convert.ts(612,17): error TS7034: Variable 'array' implicitly has type 'any[]' in some locations where its type cannot be determined.


616                 return array;
                           ~~~~~

node_modules/json2typescript/src/json2typescript/json-convert.ts(616,24): error TS7005: Variable 'array' implicitly has an 'any[]' type.


641             let array = [];
                    ~~~~~

node_modules/json2typescript/src/json2typescript/json-convert.ts(641,17): error TS7034: Variable 'array' implicitly has type 'any[]' in some locations where its type cannot be determined.


645                 return array;
                           ~~~~~

node_modules/json2typescript/src/json2typescript/json-convert.ts(645,24): error TS7005: Variable 'array' implicitly has an 'any[]' type.


660                 array[key] = this.verifyProperty(expectedJsonType[i], value[key]);
                    ~~~~~

node_modules/json2typescript/src/json2typescript/json-convert.ts(660,17): error TS7005: Variable 'array' implicitly has an 'any[]' type.


665             return array;
                       ~~~~~

node_modules/json2typescript/src/json2typescript/json-convert.ts(665,20): error TS7005: Variable 'array' implicitly has an 'any[]' type.

```

I installed the lib as usual : yarn add json2typescript, then do the import : 

```import { JsonConvert, OperationMode, ValueCheckingMode } from "json2typescript";```

TS version 2.4.1

thanks,g

**Comment by andreas-aeschlimann** [comment]
So it can be fixed by simply add the any-type at the initialisation of these variables?

**Comment by Orhleil** [comment]
Surely this should be fixed in json2typescript, as it's a better practice to always define the type of the variables in Typescript.

In the meantime, if this issue is really bothering you @xblox , you can add `"skipLibCheck": true` in your tsconfig.json file, and you shouldn't get any errors anymore. (that is, if you're using json2typescript as a dependency of course, if you're actually trying to compile it yourself, this won't help)

**Comment by xblox** [comment]
@Orhleil : thanks a lot ! FYI, skipLibCheck didn't change anything; I consider now to make a PR; let me try :-)

**Comment by lookfirst** [comment]
![image](https://user-images.githubusercontent.com/85355/29958104-37bf4cf6-8f1b-11e7-8a97-1d691b8406d4.png)

**Comment by andreas-aeschlimann** [comment]
I guess we just have to set `let array:any = []`. I actually don't know why I didn't do that in the first place. We will sure add this in the next version.

**Comment by lookfirst** [comment]
@andreas-aeschlimann When? It would be nice to quiet the errors in my IDE from your project.

**Comment by andreas-aeschlimann** [comment]
Can you please try the current version 1.0.3 and tell me if the errors have vanished, @xblox @lookfirst? I will close this issue as I suppose it is fixed.

**Comment by lookfirst** [comment]
@andreas-aeschlimann Fixed. Thanks!

**Comment by andreas-aeschlimann** [comment]
Do you know if #17 is the same thing as this issue?

**Comment by andreas-aeschlimann** [comment]
@lookfirst, do you know if #17 is the same thing as this issue?
