### ISSUE TITLE
using json2typescript in an Angular library (yeoman-generator) causes compilation failed

### ISSUE THREAD

**Issue by kirakishin** [dhlab-basel/json2typescript#25]
Hello,
iam facing to a problem using your package in an Angular library npm package generated by : 
https://github.com/jvandemo/generator-angular2-library

adding the dependency is ok, but when i start to compile with `npm run build` after created a decorated class, i got the error (rootDir error) : 
```bash
...
Error File 'C:/git/github/kirakishin/json2typescript-with-generator-angular2-library/node_modules/json2typescript/src/json2typescript/json-convert.ts' is not under 'rootDir' 'C:/git/github/kirakishin/json2typescript-with-generat
or-angular2-library/.tmp'. 'rootDir' is expected to contain all source files.
Error File 'C:/git/github/kirakishin/json2typescript-with-generator-angular2-library/node_modules/json2typescript/src/json2typescript/json-custom-convert.ts' is not under 'rootDir' 'C:/git/github/kirakishin/json2typescript-with-
generator-angular2-library/.tmp'. 'rootDir' is expected to contain all source files.

[00:53:47] 'ngc' errored after 1.51 s
[00:53:47] Error: ngc compilation failed
    at ngc.then (C:\git\github\kirakishin\json2typescript-with-generator-angular2-library\gulpfile.js:59:15)
ERROR: ngc compilation failed
...
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v7.9.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! json2typescript-with-generator-angular2-library@0.1.0 build: `gulp build`
npm ERR! Exit status 1
```
my class is in `generic.model.ts`: 
```typescripts
import {JsonObject, JsonProperty} from "json2typescript";


@JsonObject
export default class GenericModel {
    @JsonProperty("name", String)
    name: string = undefined;
}

```

You can reproduce it by cloning : 
https://github.com/kirakishin/json2typescript-with-generator-angular2-library
then : 
- `npm install`
- `npm run build`

i don't unterstand the problem : it seems the compiler wants to compile *.ts file from json2typescript.
The same appears if i only import the lib without using it : 
```typescripts
import {JsonObject, JsonProperty} from "json2typescript";
```

could you help me please ?

thanks a lot

linked issue : https://github.com/jvandemo/generator-angular2-library/issues/169

**Comment by kirakishin** [comment]
Ok, i found that if i rename all *.ts file from your library, into *.d.ts, it works !
As many libs like Angular ones, has only *.d.ts , i think , change the build process for that may the solution :)

**Comment by xblox** [comment]
same here

**Comment by kirakishin** [comment]
may i will fork this. anyone else has the same ?

**Comment by andreas-aeschlimann** [comment]
I don't really know about this, so I am not of much help. Can you make a pull request with the minimal changes that fixes it for you?

**Comment by andreas-aeschlimann** [comment]
@kirakishin do you know how we can fix this issue?

**Comment by andreas-aeschlimann** [comment]
Does it work with 1.0.5? I go ahead and close this issue, please let me know if it's okay for you now.
