### ISSUE TITLE
Feature request: Exclude

### ISSUE THREAD

**Issue by ChristianPuckSolutions** [dhlab-basel/json2typescript#31]
Hello,
As other people have commented: Great job! json2typescript is a really useful tool.

I only miss (maybe there is a way but I didn't found any) a way to exclude one property when deserializing:
```

@JsonObject
export class CustomObject {
    type: string;

    @JsonProperty('attributes', undefined, true)
    attributes: any;
}

```
If you serialize without type no issue, but if you deserialize an Instance with type then you get it on the output. 

What about:
```
@JsonObject
export class CustomObject {
    @JsonExclude
    type: string;

    @JsonProperty('attributes', undefined, true)
    attributes: any;
}
```

There is any other way to do that?

**Comment by andreas-aeschlimann** [comment]
If you don't want to use a property, you can simply drop the `@JsonProperty`decorator.

**Comment by ChristianPuckSolutions** [comment]
Hey @andreas-aeschlimann,

Thanks for your answer. But maybe I didn't explain myself clear enough:

```
@JsonObject
class Example {
  @JsonProperty('Id', String)
  id: string;

  otherField: number;

  **type: string;**

  constructor(id: string, otherField: number) {
    this.id = id;
    this.otherField = otherField;
    **this.type = 'someType';**
  }
}

let example: Example = new Example('F23213131', 2);
console.info('Serialize: ', jsonConvert.serialize(example));
try {
  console.info('Deserialize Object: ', (<any>jsonConvert).deserializeObject({ Id: 'G23213131', otherField: 2 }, Example));
} catch (e) {
  console.log((<Error>e));
}
```
Result:
```
Serialize:  {Id: "F23213131"}
Deserialize Object:  Example {id: "G23213131", otherField: undefined, **type: "someType"**}
```
I am looking for a way to avoid **type: "someType"** appearing from the Deserialization.

Thank you!

**Comment by andreas-aeschlimann** [comment]
Isn't your constructor interfering with json2typescript here? Otherwise it wouldn't be possible that otherField would be undefined instead of 2.

json2typescript calls constructor() when it creates an instance of your class. You have to catch this case in your constructor somehow, for example:

```
constructor(id: string, otherField: number) {
    if (id === undefined && otherField === undefined) return;
    this.id = id;
    this.otherField = otherField;
    this.type = 'someType';
  }
```

**Comment by ChristianPuckSolutions** [comment]
Hello @andreas-aeschlimann,

With your suggestion, I could achieve what I was looking for. Actually, I did a combination of initializing the fields to undefined or not (depending if you want it on the deserialization or not) and stopping the default constructor that uses json2typescript (all the parameters undefined) before it riches default assignation values. Doing that I am getting the expected values for serialization and deserialization. Thank you!
