### ISSUE TITLE
comments in Readme  is not true

### ISSUE THREAD

**Issue by janckerchen** [dhlab-basel/json2typescript#40]
comments in Readme

```
// This property has no @JsonProperty. 
 // It will only be mapped if our JSON object contains a key named "id".
```

it's not true,   no @JsonProperty and no map

**Comment by andreas-aeschlimann** [comment]
It is possible that this has changed in the last bigger version (1.0). I will look into this.

**Comment by nolazybits** [comment]
Yup I hit the same problem. If the @JsonProperty is not set it won't be mapped

**Comment by andreas-aeschlimann** [comment]
It is true, just add the decorator and it will work. We disabled the automatic mapping because it caused problems for serialization (reverting the mapping to json).

**Comment by nolazybits** [comment]
All good. It's actually nicer to have to specifically tell which property we want to expose to the serializer / deserializer. So 👍 . Thanks

**Comment by massimilianokraus** [comment]
v1.0.4, still the property is not mapped without the @JsonProperty decorator but still the documentation says that it does.
So every developer that tries this library trusts the fact that the decorator is not necessary, makes an app, the app does not work, he wastes time trying to figure it out, then he comes here, reads all the issues and finally understands.
Please, update the documentation, it's just 3 lines of comments...
