### ISSUE TITLE
Support for typescript Map

### ISSUE THREAD

**Issue by jifwin** [dhlab-basel/json2typescript#42]
Do you plan to support typescript's Map<?,?> as expected type? Currently I have to use "Any", otherwise deserialization fails on unknown type. By the way, very cool lib :).

**Comment by andreas-aeschlimann** [comment]
What do you need that for? Do you want to map a json object with unknown parameters to a TypeScript map?

In case that's what you want, you can use a little trick. `json2typescript` supports mapping objects to arrays out of the box. This means, you can use `[string]` as expected type, and the result will be an associative array, accessible with `array[key]`.

**Comment by jifwin** [comment]
I prepared an example:
```
      @JsonObject
      class TestBean {
        @JsonProperty("tags", Any)
        tags: Map<string, Set<string>> = undefined;
      }

      let jsonConvert = new JsonConvert();
      let serialized = {
        tags: {
          "a": [1,2,3],
          "b": [4,5,6]
        }
      };
      let deserialized = jsonConvert.deserializeObject(serialized, TestBean);
```

That trick is not enough for me, it won't validate maps values types, right?

**Comment by andreas-aeschlimann** [comment]
Try something like this:

```
@JsonObject
      class TestBean {
        @JsonProperty("tags", [[number]]) // the outer [] is for mapping the unknown props to the associative array, the inner [] is because the values are array of numbers
        tags: [string:number[]] = undefined;
      }

      let jsonConvert = new JsonConvert();
      let serialized = {
        tags: {
          "a": [1,2,3],
          "b": [4,5,6]
        }
      };
      let deserialized = jsonConvert.deserializeObject(serialized, TestBean);
```

I'm not totally sure about the key-value notation `[string: number[]]` though, but something like that exists in TypeScript.

**Comment by jifwin** [comment]
Cool! The first approach works for me. Thanks.

**Comment by andreas-aeschlimann** [comment]
That is good news. 

IMPORTANT: You need to use capital case `Number` in the `@JsonProperty` decorator, I made a mistake there.

The reason why Map/Set are difficult to use with `json2typescript` is because on runtime, generics are removed. But `json2typescript` has to check the types on runtime, not compile time, so it is not possible to use the generics.

I recommend to use it the way that is implemented above. You could however also use the `CustomConverter` approach to implement a mapping by yourself. This might be necessary, if you need to make additional checks, like checking the amount of numbers in the array.

If you use `@JsonProperty("tags", [[Number, Number, Number]])`, `json2typescript` requires you to pass at least 3 numbers in the JSON, and it should throw an error if there are less than 3.

**Comment by ahaverty** [comment]
Deserializing seems to be working with the above trick, **but doesn't seem to work for serialising:**
```typescript
        @JsonObject
        class TestBean {
            @JsonProperty("tags", [[Number]]) // the outer [] is for mapping the unknown props to the associative array, the inner [] is because the values are array of numbers
            tags: {string: number[]} = undefined;
        }

        let serialized = {
            tags: {
                "a": [1, 2, 3],
                "b": [4, 5, 6]
            }
        };
        let deserialized = jsonConvert.deserializeObject(serialized, TestBean);
        let reSerialised = jsonConvert.serialize(deserialized);

        expect(serialized).to.equal(reSerialised);
```
**With the result:**
```javascript
AssertionError: expected { Object (tags) } to equal { tags: [] }
      + expected - actual
       {
      -  "tags": {
      -    "a": [
      -      1
      -      2
      -      3
      -    ]
      -    "b": [
      -      4
      -      5
      -      6
      -    ]
      -  }
      +  "tags": []
       }
```

Any ideas on how I could easily serialise map-like properties? I'd prefer not to have to build custom converters for each property as maps in my objects are a big use case (firebase database data).
_Thanks for a great repo 👏_

**Comment by ahaverty** [comment]
`console.log(deserialized)` **gives the following:** _(notice the 0 length **"tags"** array instead of a map)_

![screen shot 2018-03-06 at 17 02 50](https://user-images.githubusercontent.com/2920947/37046430-4144c576-2160-11e8-8d36-06dd9d1bcc3c.png)

**Comment by andreas-aeschlimann** [comment]
Indeed, json2typescript doesn't map to Map, but to Array. As it is an associative array, JavaScript will return length 0 even though there are elements in it.

What does `console.log(reserialized)` show?

**Comment by ahaverty** [comment]
Thanks for the help @andreas-aeschlimann 
I modified your serializer crudely in my fork, and was close to getting maps working with a mix of your initial answer and some tricks, although it failed re-serialize correctly for non-primitive map value types. 
_(note: I'm actually using type: {string: ValueType} for the object, and parsing to Map<string, ValueType> in my get and set)_

I took your advice and created a custom converter for these types, however I need to create a new converter for each different map value type. From the looks of your answers on other issues, it's impossible to use generics to deserialize?

Do you think this library could ever work with maps natively? 🤔

_For anyone else who might come across this issue, here's my working custom serialiser:_
```typescript
@JsonConverter
export class LineItemConvert implements JsonCustomConvert<{ [key:string]: LineItem }> {
    
    private _convert: JsonConvert = new JsonConvert();
    _converter.valueCheckingMode = ValueCheckingMode.ALLOW_NULL;
    
    serialize(data: { string: LineItem }):any {
        let map: { [key:string]: any; } = {};
        _.forEach(data, (lineItem, key) => {
            map[key] = this._convert.serialize(lineItem);
        });
        return map;
    }
    deserialize(data: any): { [key:string]: LineItem } {
        let map: { [key:string]: LineItem; } = {};
        _.forEach(data, (v, k) => {
            map[k] = this._convert.deserialize(v, LineItem);
        });
        return map;
    }
}
```

**Comment by andreas-aeschlimann** [comment]
Nice! I will definitely look into it later this year. It is clear that serializing is a bit tricky, so we have to think about that as well.

**Comment by ahaverty** [comment]
I appreciate that @andreas-aeschlimann 
I've since whittled it down to a nice common abstract class. Unfortunately since the deserializer can't parse generics, I still need to extend and override the deserializer for every new value type (although it's not too bad at all). Here's a full example + classes on gist:
https://gist.github.com/ahaverty/f9cc718e43ecaf2d49f57e473b92ab64
