### ISSUE TITLE
Custom converter for array of objects

### ISSUE THREAD

**Issue by jifwin** [dhlab-basel/json2typescript#43]
Can I use custom converter to map beans in an array?

```
@JsonObject
      class TestBean {
        @JsonProperty("value", String)
        value: string = undefined;
      }

      @JsonConverter
      class TestBean2Converter implements JsonCustomConvert<TestBean2> {
        serialize(testBean2: TestBean2): any {
          [...]
        }

        deserialize(testBean2: any): TestBean2 {
          [...]
        }
      }

      @JsonObject
      class TestBean2 {
        @JsonProperty("values", TestBean2Converter)
        values: TestBean[] = [];
      }

      let jsonConvert = new JsonConvert();
      let serialized = {
        values: [
          {
            value: "a",
          },
          {
            value: "b"
          }
        ]
      };
      let deserialized = jsonConvert.deserializeObject(serialized, TestBean2);
```

In this example the whole array is passed to converter. If I use
```
@JsonProperty("values", [TestBean2Converter])
```
then it results in type error.

**Comment by andreas-aeschlimann** [comment]
No, this is not possible with the current version. But you could rewrite your converter such that it can handle an array of TestBean when serializing and deserializing!

**Comment by Sebubu** [comment]
+ 1
Would really like to see something like that

**Comment by andreas-aeschlimann** [comment]
After reading it again, I think you might misunderstood how the deserialization works. It is indeed not needed to write a custom converter in the case described above:

```
@JsonObject
class TestBean {
        @JsonProperty("value", String)
        value: string = undefined;
}

@JsonObject
class TestBean2 {
        @JsonProperty("values", [TestBean])
        values: TestBean[] = [];
}

let jsonConvert = new JsonConvert();
let serialized = {
        values: [
          {
            value: "a",
          },
          {
            value: "b"
          }
        ]
};
let deserialized = jsonConvert.deserializeObject(serialized, TestBean2);
```

This will deserialize your data without any problems.

As written 27 days ago: If you need a custom converter (if the mapping is not linear for example), then you cannot apply a custom converter to an array (yet). You have to make sure you apply the custom converter to an object instead, which is always possible with some rewriting of your code.
