### ISSUE TITLE
Fatal error in JsonConvert in angular production mode 

### ISSUE THREAD

**Issue by houssemFat** [dhlab-basel/json2typescript#44]
I'm using json2typescript to convert my json web service responses into objects with an angular 4 project. In dev mode, it works fine. But when i switch to production mode (--prod), it bugs and it try to convert another class. I'm not sure really if this is related to angular 4 compilation issue or to json2typescript.
I expect to convert a json response of class A from webservice response. In production mode, jsonconvert show an error saying that he can't find a property called "Currencies" which is not part of class A but another entierly class B.

**Comment by andreas-aeschlimann** [comment]
Hello, please provide some detailed code example so we can see the problem.

Are you sure that you don't have any circular dependencies? I usually had issues like that when circular dependencies appeared.

**Comment by houssemFat** [comment]
Thank you @andreas-aeschlimann
Here's the full scenrio : 
I have a class `CurrenciesWSResponse` for getting all curencies items
```
@JsonObject
export class CurrencyEntry{
  @JsonProperty("Country") country: string = undefined;
  @JsonProperty("Symbol") symbol: string = undefined;
}

/**
 * Response  for  Webservice Currencies ws response 
 */
@JsonObject
export class CurrenciesWSResponse extends BaseResponse {
  @JsonProperty("Currencies", [CurrencyEntry])
  list: CurrencyEntry[] = undefined;
}
``` 

and a class called ``

```

@JsonObject
export class BeneficiaryEntry {
  @JsonProperty("Name", String) name: string = undefined;
  @JsonProperty("Address") address: string = undefined;
}

/**
 * Response  for  Beneficiaries ws lisr
 */
@JsonObject
export class BeneficiariesWSResponse extends BaseResponse {
  @JsonProperty("Recipients", [BeneficiaryEntry])
  list: BeneficiaryEntry [] = undefined;
}

```

The base class is `BaseResponse`

```
@JsonObject
export abstract  class BaseResponse{
  @JsonProperty("Messages", [MessageItemDto])  messages: List<MessageItemDto> = undefined;
}
```

I'm using json2typescript to get the list of all currencies and beneficiaries by calling two http get requests 

```
getAvailableCurrencies(): Observable<CurrencyEntry[]> {
    return this.request(WS_URLS.GET_AVAILABLE_CURRENCIES_JSON, {}).map(response => this.jsonConvert.deserializeObject(response, CurrenciesWSResponse ).list);
  }
```
and 

```
fetchBeneficiariesList(): Observable<CurrencyEntry[]> {
    return this.request(WS_URLS.GET_BENEFICIARIES_LIST, {params: {}})
      .map(response => {
        let convertedResult = this.jsonConvert.deserialize(response, BeneficiariesWSResponse );
        return convertedResult.list;
      });
  }
```
I call service.fetchBeneficiariesList() and service.getAvailableCurrencies(), * it works fine in angular 4 dev mode *.
I tried to use source map files to debug production generated files, and i see that the problem is related to common inheritance, in fact, in the  `fetchBeneficiariesList` where i'm expecting to convert a list of  beneficiaries to `BeneficiariesWSResponse`, json2typescript throws an error saying that he can't find a property for a `CurrenciesWSResponse` . I'm pretty sure, it's a class inheritance issue, that's why i remove the base inheritance in CurrenciesWSResponse and it works fine. I think that's a related angular or typescript on shared inheritance.

**Comment by mikehamil10** [comment]
Came here to say I'm having a similar issue -- I've added json2typescript to my project (a mobile app built on Angular 4/Ionic/Cordova), when testing the app in dev mode its works flawlessly but when building with the AOT compiler, it just doesn't work :(

I could post my model classes but I'm using this library in a COMPLETELY standard way so I'm not sure if it would even help.

**Comment by andreas-aeschlimann** [comment]
It would probably benefit the cause if you posted a minimal example to a new Github repository. We cannot reproduce the error, neither in Angular 2/4 nor in Ionic 2/3 applications.

If you have error messages, please post them here so we can also try to understand them.

What I can say is, in Angular 4 you get warnings for circular dependencies. I am not sure if Ionic warns you about them. Having circular dependencies will cause json2typescript to fail in production. When extending classes, the risk of circular dependencies are very high. I also walked into that lately and had to fix it.

**Comment by mikehamil10** [comment]
OK I've created a minimal Ionic app that actually uses the models and modified Angular services that our production app uses (modified to return static data instead of connecting to our secure back-end):

https://github.com/mikehamil10/json2typescript-test

Here's the thing though: **_This app works in debug AND prod modes!_**

So I'm confident that the issue is somewhere in my app and not with json2typescript. So again, not sure how helpful my demo is, but at least now I can rule-out your awesome library ;)

**Comment by mikehamil10** [comment]
_(update to my previous comment)_

Great news, I fixed my problem! I think this had something specific to do with the version of Ionic + Angular my app was using.

After creating the demo app above, I compared my package.json and realized that my Ionic version was at 3.6x and my Angular version was at 4.1x. I updated everything to match the version numbers in the demo app I created (Ionic 3.9x and Angular 5.0), **and the prod build now works**!

**Comment by andreas-aeschlimann** [comment]
I don't understand why the version of Ionic or Angular would influence the behavior of `json2typescript`, because the current version comes with pre-compiled JavaScript already... But I am glad you could sort it out anyway. Let's hope @houssemFat can fix it as well.
