### ISSUE TITLE
Deserialization fails at the third time 

### ISSUE THREAD

**Issue by thomas311** [dhlab-basel/json2typescript#45]
Hi there and first of all thank you for the great work on json2typescript.
I ran into one issue which I try to solve since quiet a while and it only happens in the context of one specific class (all other objects I serialize or deserialize do not have this issue). 
When ever I request the below explained object from the server, the first 2 requests are successfully deserialized. The 3rd request always fails with a fatal error. The server response is always 100% the same.
Thank you for any suggestions or guidance.

BEGIN OF ERROR MESSAGE

Fatal error in JsonConvert. Failed to map the JSON object to the JavaScript class "ItineraryCalendar" because of a type error.
DataController.ts:271
	Class property: 
		itineraryCalendarItemArray
	Expected type: 
		[ItineraryCalendarItem,ItineraryCalendarItem,ItineraryCalendarItem,ItineraryCalendarItem,ItineraryCalendarItem,ItineraryCalendarItem,ItineraryCalendarItem,ItineraryCalendarItem,ItineraryCalendarItem,ItineraryCalendarItem,ItineraryCalendarItem,ItineraryCalendarItem,ItineraryCalendarItem,ItineraryCalendarItem,ItineraryCalendarItem,ItineraryCalendarItem,ItineraryCalendarItem,ItineraryCalendarItem,ItineraryCalendarItem,ItineraryCalendarItem,ItineraryCalendarItem,ItineraryCalendarItem,ItineraryCalendarItem,ItineraryCalendarItem,ItineraryCalendarItem,ItineraryCalendarItem,ItineraryCalendarItem,ItineraryCalendarItem,ItineraryCalendarItem,ItineraryCalendarItem,ItineraryCalendarItem,ItineraryCalendarItem,ItineraryCalendarItem,ItineraryCalendarItem,ItineraryCalendarItem,ItineraryCalendarItem,ItineraryCalendarItem,ItineraryCalendarItem,ItineraryCalendarItem,ItineraryCalendarItem,ItineraryCalendarItem,ItineraryCalendarItem,ItineraryCalendarItem,ItineraryCalendarItem,ItineraryCalendarItem,ItineraryCalendarItem,ItineraryCalendarItem,ItineraryCalendarItem,ItineraryCalendarItem,ItineraryCalendarItem,ItineraryCalendarItem,ItineraryCalendarItem,ItineraryCalendarItem,ItineraryCalendarItem,ItineraryCalendarItem,ItineraryCalendarItem,ItineraryCalendarItem,ItineraryCalendarItem,ItineraryCalendarItem,ItineraryCalendarItem,ItineraryCalendarItem,ItineraryCalendarItem,ItineraryCalendarItem,ItineraryCalendarItem,ItineraryCalendarItem,ItineraryCalendarItem,ItineraryCalendarItem,ItineraryCalendarItem,ItineraryCalendarItem,ItineraryCalendarItem,ItineraryCalendarItem,ItineraryCalendarItem,ItineraryCalendarItem,ItineraryCalendarItem,ItineraryCalendarItem,ItineraryCalendarItem,ItineraryCalendarItem,ItineraryCalendarItem,ItineraryCalendarItem,ItineraryCalendarItem,ItineraryCalendarItem,ItineraryCalendarItem,ItineraryCalendarItem,ItineraryCalendarItem,ItineraryCalendarItem,ItineraryCalendarItem,ItineraryCalendarItem,ItineraryCalendarItem,ItineraryCalendarItem,ItineraryCalendarItem,ItineraryCalendarItem,ItineraryCalendarItem,ItineraryCalendarItem,ItineraryCalendarItem,ItineraryCalendarItem,ItineraryCalendarItem,ItineraryCalendarItem,ItineraryCalendarItem,ItineraryCalendarItem,ItineraryCalendarItem,ItineraryCalendarItem]
	JSON property: 
		ItineraryCalendarItemList
	JSON type: 
		[object,object,object,object,object,object,object,object,object,object,object,object,object,object,object,object,object,object,object,object,object,object,object,object,object,object,object,object,object,object,object,object,object,object,object,object,object,object,object,object,object,object,object,object,object,object,object,object,object,object,object,object,object,object,object,object,object,object,object,object,object,object,object,object,object,object,object,object,object,object,object,object,object,object,object,object,object,object,object,object,object,object,object,object,object,object,object,object,object,object,object,object,object,object,object,object,object,object,object,object,object]
	JSON value: 
		[{"CalendarDate":"2017-11-17T00:00:00","ItineraryCount":24365},{"CalendarDate":"2017-11-18T00:00:00","ItineraryCount":14705},{"CalendarDate":"2017-11-19T00:00:00","ItineraryCount":12783},{"CalendarDate":"2017-11-20T00:00:00","ItineraryCount":13422},{"CalendarDate":"2017-11-21T00:00:00","ItineraryCount":13560},{"CalendarDate":"2017-11-22T00:00:00","ItineraryCount":12673},{"CalendarDate":"2017-11-23T00:00:00","ItineraryCount":11028},{"CalendarDate":"2017-11-24T00:00:00","ItineraryCount":9538},{"CalendarDate":"2017-11-25T00:00:00","ItineraryCount":8396},{"CalendarDate":"2017-11-26T00:00:00","ItineraryCount":9674},{"CalendarDate":"2017-11-27T00:00:00","ItineraryCount":12766},{"CalendarDate":"2017-11-28T00:00:00","ItineraryCount":13921},{"CalendarDate":"2017-11-29T00:00:00","ItineraryCount":14283},{"CalendarDate":"2017-11-30T00:00:00","ItineraryCount":13767},{"CalendarDate":"2017-12-01T00:00:00","ItineraryCount":11128},{"CalendarDate":"2017-12-02T00:00:00","ItineraryCount":8211},{"CalendarDate":"2017-12-03T00:00:00","ItineraryCount":8239},{"CalendarDate":"2017-12-04T00:00:00","ItineraryCount":9658},{"CalendarDate":"2017-12-05T00:00:00","ItineraryCount":10306},{"CalendarDate":"2017-12-06T00:00:00","ItineraryCount":10358},{"CalendarDate":"2017-12-07T00:00:00","ItineraryCount":9737},{"CalendarDate":"2017-12-08T00:00:00","ItineraryCount":8392},{"CalendarDate":"2017-12-09T00:00:00","ItineraryCount":6506},{"CalendarDate":"2017-12-10T00:00:00","ItineraryCount":6309},{"CalendarDate":"2017-12-11T00:00:00","ItineraryCount":7130},{"CalendarDate":"2017-12-12T00:00:00","ItineraryCount":7325},{"CalendarDate":"2017-12-13T00:00:00","ItineraryCount":7325},{"CalendarDate":"2017-12-14T00:00:00","ItineraryCount":6850},{"CalendarDate":"2017-12-15T00:00:00","ItineraryCount":5864},{"CalendarDate":"2017-12-16T00:00:00","ItineraryCount":4624},{"CalendarDate":"2017-12-17T00:00:00","ItineraryCount":4133},{"CalendarDate":"2017-12-18T00:00:00","ItineraryCount":4193},{"CalendarDate":"2017-12-19T00:00:00","ItineraryCount":4197},{"CalendarDate":"2017-12-20T00:00:00","ItineraryCount":4172},{"CalendarDate":"2017-12-21T00:00:00","ItineraryCount":3922},{"CalendarDate":"2017-12-22T00:00:00","ItineraryCount":3589},{"CalendarDate":"2017-12-23T00:00:00","ItineraryCount":3144},{"CalendarDate":"2017-12-24T00:00:00","ItineraryCount":2939},{"CalendarDate":"2017-12-25T00:00:00","ItineraryCount":3010},{"CalendarDate":"2017-12-26T00:00:00","ItineraryCount":3219},{"CalendarDate":"2017-12-27T00:00:00","ItineraryCount":3180},{"CalendarDate":"2017-12-28T00:00:00","ItineraryCount":2909},{"CalendarDate":"2017-12-29T00:00:00","ItineraryCount":2930},{"CalendarDate":"2017-12-30T00:00:00","ItineraryCount":2601},{"CalendarDate":"2017-12-31T00:00:00","ItineraryCount":2538},{"CalendarDate":"2018-01-01T00:00:00","ItineraryCount":2484},{"CalendarDate":"2018-01-02T00:00:00","ItineraryCount":2558},{"CalendarDate":"2018-01-03T00:00:00","ItineraryCount":2474},{"CalendarDate":"2018-01-04T00:00:00","ItineraryCount":2369},{"CalendarDate":"2018-01-05T00:00:00","ItineraryCount":2334},{"CalendarDate":"2018-01-06T00:00:00","ItineraryCount":2272},{"CalendarDate":"2018-01-07T00:00:00","ItineraryCount":2519},{"CalendarDate":"2018-01-08T00:00:00","ItineraryCount":2821},{"CalendarDate":"2018-01-09T00:00:00","ItineraryCount":2844},{"CalendarDate":"2018-01-10T00:00:00","ItineraryCount":2868},{"CalendarDate":"2018-01-11T00:00:00","ItineraryCount":2783},{"CalendarDate":"2018-01-12T00:00:00","ItineraryCount":2569},{"CalendarDate":"2018-01-13T00:00:00","ItineraryCount":2202},{"CalendarDate":"2018-01-14T00:00:00","ItineraryCount":2193},{"CalendarDate":"2018-01-15T00:00:00","ItineraryCount":2258},{"CalendarDate":"2018-01-16T00:00:00","ItineraryCount":2189},{"CalendarDate":"2018-01-17T00:00:00","ItineraryCount":2181},{"CalendarDate":"2018-01-18T00:00:00","ItineraryCount":2159},{"CalendarDate":"2018-01-19T00:00:00","ItineraryCount":2082},{"CalendarDate":"2018-01-20T00:00:00","ItineraryCount":1842},{"CalendarDate":"2018-01-21T00:00:00","ItineraryCount":1876},{"CalendarDate":"2018-01-22T00:00:00","ItineraryCount":1968},{"CalendarDate":"2018-01-23T00:00:00","ItineraryCount":1891},{"CalendarDate":"2018-01-24T00:00:00","ItineraryCount":1859},{"CalendarDate":"2018-01-25T00:00:00","ItineraryCount":1786},{"CalendarDate":"2018-01-26T00:00:00","ItineraryCount":1702},{"CalendarDate":"2018-01-27T00:00:00","ItineraryCount":1547},{"CalendarDate":"2018-01-28T00:00:00","ItineraryCount":1530},{"CalendarDate":"2018-01-29T00:00:00","ItineraryCount":1630},{"CalendarDate":"2018-01-30T00:00:00","ItineraryCount":1570},{"CalendarDate":"2018-01-31T00:00:00","ItineraryCount":1590},{"CalendarDate":"2018-02-01T00:00:00","ItineraryCount":1569},{"CalendarDate":"2018-02-02T00:00:00","ItineraryCount":1463},{"CalendarDate":"2018-02-03T00:00:00","ItineraryCount":1260},{"CalendarDate":"2018-02-04T00:00:00","ItineraryCount":1287},{"CalendarDate":"2018-02-05T00:00:00","ItineraryCount":1458},{"CalendarDate":"2018-02-06T00:00:00","ItineraryCount":1474},{"CalendarDate":"2018-02-07T00:00:00","ItineraryCount":1389},{"CalendarDate":"2018-02-08T00:00:00","ItineraryCount":1261},{"CalendarDate":"2018-02-09T00:00:00","ItineraryCount":1225},{"CalendarDate":"2018-02-10T00:00:00","ItineraryCount":1163},{"CalendarDate":"2018-02-11T00:00:00","ItineraryCount":1189},{"CalendarDate":"2018-02-12T00:00:00","ItineraryCount":1229},{"CalendarDate":"2018-02-13T00:00:00","ItineraryCount":1175},{"CalendarDate":"2018-02-14T00:00:00","ItineraryCount":1138},{"CalendarDate":"2018-02-15T00:00:00","ItineraryCount":1103},{"CalendarDate":"2018-02-16T00:00:00","ItineraryCount":1086},{"CalendarDate":"2018-02-17T00:00:00","ItineraryCount":999},{"CalendarDate":"2018-02-18T00:00:00","ItineraryCount":979},{"CalendarDate":"2018-02-19T00:00:00","ItineraryCount":1000},{"CalendarDate":"2018-02-20T00:00:00","ItineraryCount":998},{"CalendarDate":"2018-02-21T00:00:00","ItineraryCount":1008},{"CalendarDate":"2018-02-22T00:00:00","ItineraryCount":989},{"CalendarDate":"2018-02-23T00:00:00","ItineraryCount":990},{"CalendarDate":"2018-02-24T00:00:00","ItineraryCount":952},{"CalendarDate":"2018-02-25T00:00:00","ItineraryCount":906}]

Fatal error in JsonConvert. Failed to map the JSON object to the JavaScript class "ItineraryCalendarItem" because of a type error.
	Class property: 
		itineraryCount
	Expected type: 
		number
	JSON property: 
		ItineraryCount
	JSON type: 
		number
	JSON value: 
		24365
Cannot read property 'deserialize' of undefined.

END OF ERROR MESSAGE

This is how I create JsonConvert:
 ```
 this.jsonConvert=new JsonConvert();
 this.jsonConvert.operationMode = OperationMode.LOGGING; // print some debug data
 this.jsonConvert.ignorePrimitiveChecks = false; // don't allow assigning number to string etc.
 this.jsonConvert.valueCheckingMode = ValueCheckingMode.ALLOW_NULL; // allow null
```

This is where I deserialize the failing json object I receive via SignalR (remember the first 2 times doing this is perfectly fine with exactly the same json data)

```
public loadItineraryCalendar(){
        let fromDate = this.getDateString(currentDate);
        this.signalRService.dataProxy.invoke('LoadItineraryCalendar', fromDate ).done((result:any) => {
            let r = this.jsonConvert.deserialize(result,ItineraryCalendar);
            this.itineraryCalendarReceivedSubject.next(r);
        });
    }
```

This is the class 'ItineraryCalendar' being used:

```
import {JsonObject, JsonProperty} from "json2typescript";
import {ItineraryCalendarItem} from './ItineraryCalendarItem';
@JsonObject
export class ItineraryCalendar {
    @JsonProperty('ItineraryCalendarItemList', [ItineraryCalendarItem], true)
    public itineraryCalendarItemArray:ItineraryCalendarItem[];
    @JsonProperty('EntityId', Number, true)
    public entityId:number;
    @JsonProperty('EntityType', Number, true)
    public entityType:number; //currently can be polygon(1),hotel(3),country(4),region(5)
    @JsonProperty('CountryCode', String, true)
    public countryCode:string;
    @JsonProperty('RegionCodeList', [String], true)
    public regionCodeArray:string;

    constructor(){
        this.itineraryCalendarItemArray=undefined;
        this.entityId=undefined;
        this.entityType=undefined;
        this.countryCode=undefined;
        this.regionCodeArray=undefined;
    }
}

```
And this is the class 'ItineraryCalendarItem' being used:

```
import {JsonObject, JsonProperty} from "json2typescript";
import {DateConverter} from '../converters/jsonConverters';

@JsonObject
export class ItineraryCalendarItem {
    @JsonProperty('CalendarDate', DateConverter, true)
    public calendarDate:Date;
    @JsonProperty('ItineraryCount', Number, true)
    public itineraryCount:number;

    constructor(){
        this.calendarDate=undefined;
        this.itineraryCount=undefined;
    }
}
```

The DateConverter is defined like this:
```
@JsonConverter
class DateConverter implements JsonCustomConvert<Date> {
    serialize(date: Date): string {
        let yyyy=date.getFullYear().toString();
        let mm=(date.getMonth() + 1).toString();
        if(mm.length==1) mm='0'+mm;
        let dd=date.getDate().toString();
        if(dd.length==1) dd='0'+dd;
        let hh=date.getHours().toString();
        if(hh.length==1) hh='0'+hh;
        let MM=date.getMinutes().toString();
        if(MM.length==1) MM='0'+MM;
        let ss=date.getSeconds().toString();
        if(ss.length==1) ss='0'+ss;

        return yyyy + "-" + mm+ "-" + dd + "T" + hh + ":" + MM + ":" + ss;
    }
    deserialize(date: string): Date {
        if(date!=undefined) return new Date(date);
        else return undefined;
    }
}
```

**Comment by andreas-aeschlimann** [comment]
What happens if you just remove the two lines of the first or second property of `ItineraryCalendarItem`? 

For example for the first property like this:

```
//@JsonProperty('CalendarDate', DateConverter, true)
//public calendarDate:Date;
```

Does it work without any issue?

**Comment by thomas311** [comment]
If I remove the first 2 lines it still produces the same error (at the third time)
If I remove the second 2 lines it runs with no problems (tried it 10 times - no issue)
This one worked:


```
@JsonObject
export class ItineraryCalendarItem {
    @JsonProperty('CalendarDate', DateConverter, true)
    public calendarDate:Date;
    //@JsonProperty('ItineraryCount', Number, true)
    //public itineraryCount:number;

    constructor(){
        this.calendarDate=undefined;
       //this.itineraryCount=undefined;
    }
}

```

**Comment by andreas-aeschlimann** [comment]
Are you sure it's fine to set undefined in the constructor? Just to be sure I would try to set `= undefined` immediately at property declaration.

The error does not make a lot of sense, it basically means it tries to apply a custom converter to your number, and it shouldn't do that. If the above does not work, try this for "fun":

```
@JsonProperty('ItineraryCount', Any, true)
public itineraryCount:number;
```

while Any has to be imported from `json2typescript`.

**Comment by thomas311** [comment]
Thank you for working with me on that!
I set undefined on all my classes in the constructor with no issues (in terms of code-readability I might reconsider this). 
But I did what you suggested and set undefined right at declaration: no success.
I tried 'Any' as you suggested: no success.
Any other ideas?

**Comment by thomas311** [comment]
the strange thing is that the except same code runs fine twice and then produces the error always exactly at the third time. I like to think if this was a general coding issue then it would break right away, but it doesn't.

**Comment by andreas-aeschlimann** [comment]
Can you set up a minimal angular project and post it on a new github repository? I will have a look at it.

**Comment by thomas311** [comment]
Will try to get that done in the next few days.
Thank you!

**Comment by thomas311** [comment]
I made a simple test project today and the error does not happen (so I didn't even bother posting it).
In both projects I use the exact same packages and versions.
I simplified the original project to just take a short json string and deserialize it = >fails as usual.
In the test project the exact same lines of code (copy and past) run fine.
I'm down to this code:

```
this.jsonConvert=new JsonConvert();
this.jsonConvert.operationMode = OperationMode.LOGGING; // print some debug data
this.jsonConvert.ignorePrimitiveChecks = false; // don't allow assigning number to string etc.
this.jsonConvert.valueCheckingMode = ValueCheckingMode.ALLOW_NULL; // allow null

let testjson='{"ItineraryCalendarItemList":[{"CalendarDate":"2017-11-19T00:00:00","ItineraryCount":16},{"CalendarDate":"2017-11-20T00:00:00","ItineraryCount":17},{"CalendarDate":"2017-11-21T00:00:00","ItineraryCount":16},{"CalendarDate":"2017-11-22T00:00:00","ItineraryCount":11}],"EntityType":1,"EntityId":1718,"CountryCode":null,"RegionCodeList":null}';
let jsonObj = JSON.parse(testjson)
let r = this.jsonConvert.deserialize(jsonObj,ItineraryCalendar);
```

So it must be some sort of dependency, or some setting which messes my original project up so that the 3rd time deserializing this string, fails (and so far only this string, I deserialize over 30 other classes just fine)
I can execute above code fine 2 times and then the 3rd time breaks again.
The original project is too large to start moving stuff out or into the test project.
Any ideas what else could cause this?

**Comment by andreas-aeschlimann** [comment]
`json2typescript` will fail if you have circular dependencies. Chances are high, that your large project somewhere has a circular dependency on the classes you are trying to work with.

I would try the following things:
- Have a look at the places where you include your classes.
- Rename the classes AND property names in the code that cause issues (not in the JSON obviously)

It must be possible to isolate the issue and get to the fail somehow.

**Comment by thomas311** [comment]
I think you nailed it: I copied the 2 classes in questions under a different class name and used them at only one point inside my project to deserialize the json message and it worked with no problem.
Now I just have to find out where exactly I messed up. will keep you posted. Thank you for your excellent guidance!

**Comment by thomas311** [comment]
OK, here is the reason and the solution, even though I don't completely understand it yet:
The object 'ItineraryCalendar' was bound as data source to a kendo-chart-series-item (Telerik KendoUI for Angular). 

When the whole thing failed it looked like this:

`<kendo-chart-series-item type="line" *ngIf="data" [data]="data.itineraryCalendarItemArray" field="itineraryCount" categoryField="calendarDate"> </kendo-chart-series-item>`

where 'data' was of type 'ItineraryCalendar'.
The component containing this kendo widget also had the button i clicked upon which the data loading and json deserialization was triggered. So this component was open and active at the time of error.

As soon as i removed the binding for [data] everything worked fine.
Overall this looks like a bug to me in the kendo widget, as data binding as such shouldn't cause the issue imho.
So for now I changed [data]="data.itineraryCalendarItemArray"  to [data]="chartData" to decouple the widget from my class, and in the ts file behind it looks like this now:
```

private chartData:any[];
    set data(ic:ItineraryCalendar){
        this.chartData=new Array<any>();
        for(var item of ic.itineraryCalendarItemArray){
            let d={itineraryCount:item.itineraryCount, calendarDate:item.calendarDate};
            this.chartData.push(d);
        }
    }
 

```
Again, I don't completely understand why the data binding as I had it caused the problem, but if you feel like I do that it shouldn't cause the problem, I will report this to Telerik, even though it will be hard for me to provide them with a sample to work from.
What do you think?

**Comment by andreas-aeschlimann** [comment]
Good that you have found the source and a workaround. 

At this moment I cannot imagine how `json2typescript` could be responsible for the issues, and your project seems to be complicated enough so it is basically impossible to understand what is going on.

I cannot really help you any further because I don't know KendoUI at all. It looks like a nice project though, could be interesting for us too.

**Comment by thomas311** [comment]
I don't think its a json2typescript issue at all. I will open a case with Telerik and see what they say. At least I have a workaround thanks to your great and fast help! 
Thank you again und Gruesse in die Schweiz.
