### ISSUE TITLE
Question:  json annotations 

### ISSUE THREAD

**Issue by figuerres** [dhlab-basel/json2typescript#46]
I have to deal with some OData 4  web services that return a number of items in the form of @odata.thing

like "@odata.count" : 196

for most json i create an interface with items like
count: number;

and if the json is "count" : 196  life is good.
but the @odata.count is a problem.
can this package map them  ??

or do i need to look else where ??

I am looking for any example of someone working with this but no luck so far.

**Comment by andreas-aeschlimann** [comment]
Hi, yes this will work without any problems.

There are dozens of examples in the readme. Just follow it and you will be able to make it work as you wish.

```
@JsonObject
export class Data {

    @JsonProperty("@odata.count", Number)
    count: number = undefined;

}
```

and

```
const jsonConvert = new JsonConvert();
jsonConvert.deserialize(jsonObject, Data); // jsonObject is your original object from the webserver
```

Good luck!
