### ISSUE TITLE
Cannot deserialize classes with generics

### ISSUE THREAD

**Issue by AlexanderKiriluyk** [dhlab-basel/json2typescript#49]
How to deserialize such a class?
`jsonConvert.deserializeObject(data, SearchPageData<ProductData>;`

**Comment by andreas-aeschlimann** [comment]
Generics is an abstraction that does not exist on compile time. `json2typescript` is designed to run on compile time, so it cannot work with that.

I have not tried it yet, but there are surely ways to use it. You just have to make sure that you analyze what's happening with your classes on compile time.

**Comment by andreas-aeschlimann** [comment]
Due to inactivity, I'm going to close this issue.
