### ISSUE TITLE
Recursive deserializaton failed

### ISSUE THREAD

**Issue by veznidav** [dhlab-basel/json2typescript#50]
I have custom converter:
```javascript
@JsonConverter
export class InstructionConverter implements JsonCustomConvert<DrawingInstruction> {
...
 deserialize(instruction: any): DrawingInstruction {
        const jsonConverter: JsonConvert = new JsonConvert();
        switch (instruction.type) {
            case "DrawShape": {
                return jsonConverter.deserializeObject(instruction, DrawShape);
            }
            case "DrawString": {
                return jsonConverter.deserializeObject(instruction, DrawString);
            }
...
```
Imagine a situation where this converter is deserializing `DrawShape` object. The `DrawShape` object can contain property of type `DrawingInstruction` that should be deserialized also by this `InstructionConverter`

```javascript
@JsonObject
export class DrawShape implements DrawingInstruction  {
    @JsonProperty("instruction", InstructionConverter)
    str: DrawingInstruction = undefined;
...
```
Every time this happens the deserialization failed. Is there some limitation that I can not use a custom converter recursively?

**Comment by andreas-aeschlimann** [comment]
Unfortunately this is probably a use case that has not been tested enough. Could you provide a minimal HelloWorld example project where you run into the problems? You can post the project then to Github and I will be happy to work through the issues if possible.

**Comment by andreas-aeschlimann** [comment]
Due to inactivity, I'm going to close this issue.
