### ISSUE TITLE
Why do we need to set undefined on the properties for the mapper to work?

### ISSUE THREAD

**Issue by nolazybits** [dhlab-basel/json2typescript#52]
And could we have it so we don't have to do this?
That would be nice(r) 😃

**Comment by andreas-aeschlimann** [comment]
You can assign any value you'd like. It can be null, the initial value or undefined.

It is only possible to drop the initial assignment if we worked with reflection methods (see pull request). We did not implement this yet; one of the reasons is that we like the fact that no dependencies are needed as of now.

**Comment by nolazybits** [comment]
What pull request is it.
Not having to manually assign value to the variable for all properties of all objects against having one dependency I personally would prefer to have the dependency :) 
Thanks for your answer. I hope this PR will be merge soon :+1:

**Comment by andreas-aeschlimann** [comment]
I understand - it depends on your structure.

In general, I suppose typing the decorators already needs some work, so it does not hurt much more to initialize the properties.

I will look at the PR for sure, but there are other priorities at the moment unfortunately. And we don't wanna break anything for the hundreds of users our library already has!

FYI, I'll go ahead and close this issue as it is already covered by the PR.
