### ISSUE TITLE
JsonIgnore

### ISSUE THREAD

**Issue by MetaiR** [dhlab-basel/json2typescript#55]
hi,
I have used a similar library for java named `Jackson`.
it has a annotation called `@JsonIgnore` which can be used for a property that want to not consider from a json and also prevent to convert in a json.

what is the synonim of `JsonIgnore` in this library?

**Comment by andreas-aeschlimann** [comment]
There is no need for that, because all properties not having a `@JsonProperty` will be automatically ignored.
