### ISSUE TITLE
error on null value

### ISSUE THREAD

**Issue by MetaiR** [dhlab-basel/json2typescript#56]
hello again,

I'm getting my json from the server via an API.
sometimes according to server database, some of json properties are null and this cause error:

like this:

	Fatal error in JsonConvert. Failed to map the JSON object to the JavaScript class "MessageModel" because of a type error.

	Class property: 
		_desc

	Expected type: 
		string

	JSON property: 
		message_desc

	JSON type: 
		null

	JSON value: 
		null

	Reason: Given value is null.

**Comment by MetaiR** [comment]
can be fixed by:
`ValueCheckingMode.ALLOW_NULL`

**Comment by andreas-aeschlimann** [comment]
Indeed:

TypeScript developers to disallow null in applications, so no property can ever be null. However, I like to have the possibility to set objects to null or even primitives to null (useful for classes coming from database tables with nullable foreign key fields). That is why there are three ways how to handle null in json2typescript.
