### ISSUE TITLE
.js.map comments in js files

### ISSUE THREAD

**Issue by joshpainter** [dhlab-basel/json2typescript#60]
These comments in the js files give me warnings when I compile. I'm using json2typescript in my React project, installed using npm. When I npm start to run the React app, I see warnings about these lines. The link below is one example but these comments exist in all the js files.

https://github.com/dhlab-basel/json2typescript/blob/97d2600677870176d03aafb2b9de2ec1d04f647b/src/json2typescript/any.js#L8

**Comment by andreas-aeschlimann** [comment]
Thanks for your report, this wasn't intended and I will try to remove them in the next release.
