### ISSUE TITLE
Abbility to set custom IDs for classes

### ISSUE THREAD

**Issue by archfz** [dhlab-basel/json2typescript#66]
The constructor.name is a dangerous thing to rely on. It can cause problems and I have even encountered them. The option to add explicit @JsonObject ID would solve this issue.
I have implemented this on the MR: https://github.com/dhlab-basel/json2typescript/pull/65

**Comment by andreas-aeschlimann** [comment]
Thanks, that is true. I will put it on the to-do list and review everything when I have time.
