### ISSUE TITLE
class from/to array mapping

### ISSUE THREAD

**Issue by AntonPilyak** [dhlab-basel/json2typescript#74]
I have a JSON structure like below:
```
{
     fieldOne: valueOne,
     fieldTwo: [arrayVal1, arrayVal2, arrayVal3]  //not like this: {someName: [arrayVal1, arrayVal2, arrayVal3]}
}
```

and I want it to be mapped into two classes, ClassA and ClassB with the following structure:
```
@JsonObject('someNameA')
ClassA{
    @JsonProperty('fieldOne', String)
    fieldOne: string;      //no problem here
    fieldTwo:  ClassB;    //Class B should be build from array somehow, but it seems to be impossible.
}
```

```
@JsonObject('someNameB')
ClassB{
  //have no clue how to annotate this class to map it's values from array without having a field name
  //suggest it is impossible
   val1: number;
   val2: number;
   val3: number;
}
```

If this really is not implemented, I would suggest to add a possibility for mapping objects directly to JSON types (like array), without obligation to have named fields. If this is possible now, please, give me an example of how to do it.

**Comment by andreas-aeschlimann** [comment]
Is there some specific reason why `fieldTwo` is not allowed to be a number array?

Anyway, there is a simple solution for your problem. Just use the custom converter as described in the ReadMe to deserialize and serialize your data as you like. If you use a custom converter, you are responsible for throwing errors, so you can handle things like: length of the fieldTwo array, types of the elements, etc.

**Comment by andreas-aeschlimann** [comment]
You can reuse the same custom converter wherever ClassB is used, so this should work without any big efforts.

**Comment by AntonPilyak** [comment]
indeed, thanks a lot for your help!

**Comment by andreas-aeschlimann** [comment]
Great! It would be nice if you could share the custom converter, so other people who learn about this package can profit from it.
