### ISSUE TITLE
Files from /src not found

### ISSUE THREAD

**Issue by CharbelIlias** [dhlab-basel/json2typescript#76]
Im getting 404s on all files from inside /src/json2typescript when I use this package. In my systemjs use the path /node_modules/json2typescript/index.js'. 

Have I missed something?

**Comment by andreas-aeschlimann** [comment]
This is the same as #72, most likely.

I don't know how to fix it, I saw it once and then the error disappeared...

What setup do you use? I have only tried Angular and Ionic CLI projects so far (using WebPack).

**Comment by CharbelIlias** [comment]
Interesting, thanks for the link, but his/her solution did not work for me...
My setup is a .NET framework application that I've added Angular 5 to. No CLI, no WebPack. But I use Gulp to load/build.  I've been trying to solve this for two days now..

**Comment by andreas-aeschlimann** [comment]
If you go back to the previous version, does the problem occur as well?

**Comment by CharbelIlias** [comment]
I solved this by adding this to 'packages' in systemjs.config.js:
            json2typescript: {
                defaultExtension: 'js',
                main: 'index.js'
            }

**Comment by andreas-aeschlimann** [comment]
Do you think this is a SystemJS-only related issue? Is there a way we can provide a fix generically?

**Comment by CharbelIlias** [comment]
Im not sure, I have only used this package on one Angular project. But I would atleast recommend a more in-depth README for getting this up and running on Angular, where you add this line as a possible way to make it run, because this took me almost two days to get right..

**Comment by musicEnfanthen** [comment]
This seems to be the usual way to embedd external packages with SystemJS, isn't it? (cf. https://github.com/systemjs/systemjs/blob/master/docs/config-api.md#packages )

**Comment by andreas-aeschlimann** [comment]
I haven't worked with SystemJS since the very first betas of Angular, so I don't know.

But in that case I suppose we do not have to react to this issue (immediately).
