### ISSUE TITLE
Case insensitive property lookup?

### ISSUE THREAD

**Issue by onionhammer** [dhlab-basel/json2typescript#81]
I'm trying to utilize this because we get some inconsistent cases from lots of different source, but it looks like it is case sensitive

Is there a way to configure JsonProperty() to not have a case sensitive name

**Comment by onionhammer** [comment]
@andreas-aeschlimann yeah thats probably the best bet... but you would have to do every permutation;

For instance these should all be valid:

parameterId
parameterID
ParameterId
ParameterID

**Comment by andreas-aeschlimann** [comment]
Todo: case insensitive mode

**Comment by andreas-aeschlimann** [comment]
This has been implemented and will be included in the new version 1.0.7.
