### ISSUE TITLE
OperationMode.DISABLE constructor param has no effect

### ISSUE THREAD

**Issue by dleavitt** [dhlab-basel/json2typescript#82]
Since the value of `OperationMode.DISABLE` is 0, it fails the first clause in this check and the operationMode stays at `1`:
https://github.com/dhlab-basel/json2typescript/blob/master/src/json2typescript/json-convert.ts#L134

Bug or unintentional feature? :)

**Comment by andreas-aeschlimann** [comment]
Lol funny "feature". Thanks for the report, will fix it of course.

Tests should also cover this case. I thought they did, apparently, they don't.

**Comment by andreas-aeschlimann** [comment]
Fixed in new commit
