### ISSUE TITLE
How to map union types 

### ISSUE THREAD

**Issue by davidonlaptop** [dhlab-basel/json2typescript#9]
In typescript, you can do this:
```
class Story {
  name: String;
}
class Travel {
  story: boolean | Story;
}

var travelA:Travel = {story: true};
var travelB:Travel = {story: {name:"Best time in Nepal"}}
```

How to deserialize travelA and travelB with json2typescript ?

**Comment by andreas-aeschlimann** [comment]
As of now, there is no union type.

But you can deserialize it with "any", but then no type checking is done for your property story in Travel.

Soon we are going to add custom deserialization, so then it should be possible. I will keep this issue open to make sure we will look into it.

**Comment by davidonlaptop** [comment]
thanks @andreas-aeschlimann

**Comment by andreas-aeschlimann** [comment]
I don't think this will be possible directly, except by custom converters as discussed in #6.

I am going to implement #6 and close this issue for now. Hopefully, you can use it the way that is planned.
