### ISSUE TITLE
Multiple decorators error in 1.1.1

### ISSUE THREAD

**Issue by depl0y** [dhlab-basel/json2typescript#90]
Today I upgraded to version 1.1.1, but it seems that multiple decorators are no longer allowed on properties?

```
	@JsonProperty('PostalCode', String, true)
	@JsonProperty('Zipcode', String, true)
	public zipcode: string = undefined;
```

This results in the following error:

```
Uncaught Error: Fatal error in JsonConvert. It is not allowed to add multiple decorators for the same property.

	Class property: 
		zipcode
```

In version 1.0.6 this works as expected.

**Comment by depl0y** [comment]
Seems, this might be a duplicate of https://github.com/dhlab-basel/json2typescript/issues/88

**Comment by andreas-aeschlimann** [comment]
Hi @depl0y 

Two decorators actually never worked. Since 1.1.0 it throws an error because otherwise people would think it works!

There was indeed a pull request but it raised some new issues, hence it was postponed.

**Comment by andreas-aeschlimann** [comment]
I'm closing this in favor of #88, please feel free to respond here or there.
