### ISSUE TITLE
is it safe to do all converting with same instance

### ISSUE THREAD

**Issue by MetaiR** [dhlab-basel/json2typescript#95]
hi,
I just want to know is it safe or I have to create a new instance for each convert situations I have?

**Comment by andreas-aeschlimann** [comment]
Yes, it is safe and – most of the times – preferred.

Having multiple instances is only necessary when you have different API's or different behavior in some classes of your code.

**Comment by MetaiR** [comment]
tnx for ur answer, please add this note somewhere inside your Readme.md
