### ISSUE TITLE
Cannot access 'x' before initialization

### ISSUE THREAD

**Issue by niveo** [dhlab-basel/json2typescript#99]
> typescript: 3.4.5
> angular: 8.0.0-rc.4
> json2typescript: 1.2.3

```
@JsonObject("ConfTable")
export class ConfTable {
  id: number;
  @JsonProperty("idField", ConfField)
   idField: ConfField  = undefined;;
}
@JsonObject("ConfField")
export class ConfField{
   id: number;
    @JsonProperty("confTable", ConfTable)
    confTable: ConfTable  = undefined;;
}
```
Error: Cannot access 'ConfField' before initialization

I have a circular dependency that is generating an error, does anyone know how to solve it?

**Comment by andreas-aeschlimann** [comment]
I'll show it by an example how you can resolve a circular dependency:

Consider this circular dependency `FootballGame => FootballLeague => FootballGame`:

```
export class FootballGame {
    // Some properties
    id: number;
    // Circular property
    league: FootballLeague;
}

export class FootballLeague {
    // Some properties
    id: number;
    // Circular property
    games: FootballGame[];
}
```

Pick now one of the two classes and create a parent class or interface. Your new structure might create the dependencies `FootballGame => IFootballLeague, FootballLeague => IFootballLeague`, but there is no circular dependency anymore:

```
export class FootballGame {
    // Some properties
    id: number;
    // Circular property
    league: IFootballLeague;
}

export class FootballLeague extends IFootballLeague {
    // Circular property
    games: FootballGame[];
}

export class IFootballLeague {
    // Some properties
    id: number;
}
```

**Comment by ben12** [comment]
But we cannot define the json2typescript conversion configuration, because it restore the dependency:

```typescript
@JsonObject("FootballGame")
export class FootballGame {
    // Some properties
    @JsonProperty("id", Number)
    id: number;
    // Circular property
    @JsonProperty("league", FootballLeague) // <== Here
    league: IFootballLeague;
}
```

So, how to do ?

**Comment by andreas-aeschlimann** [comment]
> But we cannot define the json2typescript conversion configuration, because it restore the dependency:
> 
> ```ts
> @JsonObject("FootballGame")
> export class FootballGame {
>     // Some properties
>     @JsonProperty("id", Number)
>     id: number;
>     // Circular property
>     @JsonProperty("league", FootballLeague) // <== Here
>     league: IFootballLeague;
> }
> ```
> 
> So, how to do ?

Why not using IFootballLeague in the `@JsonProperty` decorator? This is how we do it as well.

**Comment by ben12** [comment]
I get this error:
```
'IFootballLeague' only refers to a type, but is being used as a value here.
```

**Comment by andreas-aeschlimann** [comment]
> I get this error:
> 
> ```
> 'IFootballLeague' only refers to a type, but is being used as a value here.
> ```

Is IFootballLeague a class (not interface) and defined in its own file?

**Comment by ben12** [comment]
Ok, sorry, in my case `IFootballLeague` is an interface :/

My modèle is complex and i migrate it to use json2typescript, but i get a lot of "Circular dependency detected".
I have solved it for the now by using `@JsonProperty("league", Any)` to break the circular dependencies.

**Comment by andreas-aeschlimann** [comment]
> Ok, sorry, in my case `IFootballLeague` is an interface :/
> 
> My modèle is complex and i migrate it to use json2typescript, but i get a lot of "Circular dependency detected".
> I have solved it for the now by using `@JsonProperty("league", Any)` to break the circular dependencies.

Interfaces get removed after compilation, so you need to use classes. Then it will work without problems with the approach I gave above!
